version: '3.8'

volumes:
  postgres_data:

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /project/manage.py runserver 0.0.0.0:8000
    container_name: quiz-django
    volumes:
      - .:/quiz:cached
    ports:
      - "8005:8000"
    depends_on:
      - postgres
  postgres:
    build:
      context: .
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: quiz-db
    hostname: postgres
    env_file:
      - .env
