version: '3.8'
volumes:
  postgres_data:

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-django
    volumes:
      - .:/quiz:cached
    ports:
      - "8080:8000"
    depends_on:
      - postgres
  postgres:
    build:
      context: .
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: quiz-db
    hostname: postgres
    ports:
      - "5432"
    env_file:
      - .env
