version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/quiz:cached
    ports:
      - "8080:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: quiz-db
    hostname: postgres
    env_file:
      - .env

volumes:
  postgres_data:
